[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_project = "E4VK7K5JeQdsCSrcNAGp5sCC89ntFYrddTr7XYdYjtpN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/escrow_project-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
